### ISSUE TITLE
Evaluation run fails with `ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by mhuesch** [GaloisInc/ppaml-cp5#17]
[This file](https://github.com/GaloisInc/ppaml-cp5/files/14628/symptomatic_command.txt) shows the ouput of a `peval evaluate` execution in which an index out of bounds exception occurs.

The run I was trying to evaluate produced these 3 files: [pcfgla.grammar.txt](https://github.com/GaloisInc/ppaml-cp5/files/14630/pcfgla.grammar.txt), [pcfgla.lexicon.txt](https://github.com/GaloisInc/ppaml-cp5/files/14631/pcfgla.lexicon.txt), [pcfgla.states.txt](https://github.com/GaloisInc/ppaml-cp5/files/14629/pcfgla.states.txt). I had to add the '.txt' extension so GitHub would let me upload them - you might have to rename the files to get `eval.sh` to accept them. HeHe, could you try to reproduce this crash? Thanks!

(and let me know if there are other helpful details I can provide for tracking this down)

**Comment by hhexiy** [comment]
This is because the grammar file contains 2 rules:
W_0 -> a_0 0.04
 FW_0 -> d_0 e_0 0.08

However, the state file does not have states "a", "d", "e".

I would suggest to have a script to check if the grammar files are valid,
e.g. states in grammar files are all in state files and the number of
states are consistent.

**Comment by mhuesch** [comment]
@hhexiy cool, thanks!

I have added a script to do such checking in 01ec9594 and dd160d4f.

I'm going to close this since it's a "solution error".
