### ISSUE TITLE
`evalb` segfaults

### ISSUE THREAD

**Issue by mhuesch** [GaloisInc/ppaml-cp5#21]
Trying to evaluate a run just now, I got this
```
/tmp/peval.T0M0xk.UNDECIDED/evaluator/eval.sh: line 98:  6935 Segmentation fault      (core dumped) $evalb -p ${evalb_param} ${gold_file} ${parsed_file} > ${eval_file}
evaluating exited with return code 139
```

This was doing the eighth size dataset - the micro and sixteenth sized ones evaluated fine. Hehe, have you encountered this before? Perhaps it is running out of memory?

**Comment by hhexiy** [comment]
Hmm..I don't think it's out-of-memory. I have evaluated on the entire
dataset before. There might be something wrong with the parsed file.

**Comment by mhuesch** [comment]
Ok, I will send you an email with the files (just to keep confidentiality).

**Comment by hhexiy** [comment]
The problem is the line

#define MAX_BRACKET_IN_SENT     200

I don't know why but this output has much larger number of brackets that is
uncommon for a parse tree. I just increased this value to 500 (change
pushed) and it seems to be working. Also, I noticed that evalb reported
invalid parses that have unmatched brackets for this output.

**Comment by mhuesch** [comment]
Ah awesome, thanks for the fast response!!! I kicked off a rerun of the evaluations this morning and they seem to be working.
